# Generated by Django 4.2.5 on 2023-10-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=5, unique=True)),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.CharField(max_length=10)),
                ('admission_date', models.DateField()),
                ('ward_number', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
